apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      
      containers:
      - name: flask-api
#         image: idrisniyi94/python-flask-api:2.0
          image: okteto.dev/flask-api:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
  - port: 5001
    targetPort: 5000
